/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoConfiguracoesGrafico.java
 *
 * Created on Oct 11, 2011, 2:06:11 PM
 */
package projetofisicamovimento.ig;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author David
 */
public class DialogoConfiguracoesGrafico extends javax.swing.JDialog {

    private PainelGrafico painelGrafico;
    
    /** Creates new form DialogoConfiguracoesGrafico */
    public DialogoConfiguracoesGrafico( 
            java.awt.Frame parent, 
            PainelGrafico painelGrafico,
            boolean modal ) {
        super( parent, modal );
        initComponents();
        this.painelGrafico = painelGrafico;
        
        switch ( this.painelGrafico.getTipoGrafico() ) {
            case ET:
                radioET.setSelected( true );
                break;
            case AT:
                radioAT.setSelected( true );
                break;
            case VT:
                radioVT.setSelected( true );
                break;
        }
        
        painelCorET.setBackground( this.painelGrafico.getCorPontosET() );
        painelCorAT.setBackground( this.painelGrafico.getCorPontosAT() );
        painelCorVT.setBackground( this.painelGrafico.getCorPontosVT() );
        checkMostrarValores.setSelected( this.painelGrafico.isMostrarValores() );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        painelTipoDesenho = new javax.swing.JPanel();
        radioET = new javax.swing.JRadioButton();
        radioAT = new javax.swing.JRadioButton();
        radioVT = new javax.swing.JRadioButton();
        painelConfiguracoes = new javax.swing.JPanel();
        labelCorET = new javax.swing.JLabel();
        labelCorAT = new javax.swing.JLabel();
        labelCorVT = new javax.swing.JLabel();
        painelCorET = new javax.swing.JPanel();
        painelCorAT = new javax.swing.JPanel();
        painelCorVT = new javax.swing.JPanel();
        checkMostrarValores = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações do Gráfico");

        painelTipoDesenho.setBorder(javax.swing.BorderFactory.createTitledBorder("Desenhar Gráfico"));

        buttonGroup.add(radioET);
        radioET.setSelected(true);
        radioET.setText("Espaço X Tempo");

        buttonGroup.add(radioAT);
        radioAT.setText("Aceleração X Tempo");

        buttonGroup.add(radioVT);
        radioVT.setText("Velocidade X Tempo");

        javax.swing.GroupLayout painelTipoDesenhoLayout = new javax.swing.GroupLayout(painelTipoDesenho);
        painelTipoDesenho.setLayout(painelTipoDesenhoLayout);
        painelTipoDesenhoLayout.setHorizontalGroup(
            painelTipoDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoDesenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTipoDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioET)
                    .addComponent(radioAT)
                    .addComponent(radioVT))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        painelTipoDesenhoLayout.setVerticalGroup(
            painelTipoDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoDesenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioET)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVT)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        painelConfiguracoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        labelCorET.setText("Cor SxT:");

        labelCorAT.setText("Cor AxT:");

        labelCorVT.setText("Cor VxT:");

        painelCorET.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelCorET.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorETMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorETLayout = new javax.swing.GroupLayout(painelCorET);
        painelCorET.setLayout(painelCorETLayout);
        painelCorETLayout.setHorizontalGroup(
            painelCorETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorETLayout.setVerticalGroup(
            painelCorETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        painelCorAT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelCorAT.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorAT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorATMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorATLayout = new javax.swing.GroupLayout(painelCorAT);
        painelCorAT.setLayout(painelCorATLayout);
        painelCorATLayout.setHorizontalGroup(
            painelCorATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorATLayout.setVerticalGroup(
            painelCorATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        painelCorVT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelCorVT.setMaximumSize(new java.awt.Dimension(20, 20));
        painelCorVT.setMinimumSize(new java.awt.Dimension(20, 20));
        painelCorVT.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorVT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorVTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorVTLayout = new javax.swing.GroupLayout(painelCorVT);
        painelCorVT.setLayout(painelCorVTLayout);
        painelCorVTLayout.setHorizontalGroup(
            painelCorVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorVTLayout.setVerticalGroup(
            painelCorVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        checkMostrarValores.setText("Mostrar Valores");

        javax.swing.GroupLayout painelConfiguracoesLayout = new javax.swing.GroupLayout(painelConfiguracoes);
        painelConfiguracoes.setLayout(painelConfiguracoesLayout);
        painelConfiguracoesLayout.setHorizontalGroup(
            painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCorET, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCorAT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCorVT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                        .addComponent(painelCorET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkMostrarValores))
                    .addComponent(painelCorAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCorVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        painelConfiguracoesLayout.setVerticalGroup(
            painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelCorET)
                    .addComponent(painelCorET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkMostrarValores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelCorAT)
                    .addComponent(painelCorAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(painelCorVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorVT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConfiguracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTipoDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTipoDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-334)/2, (screenSize.height-329)/2, 334, 329);
    }// </editor-fold>//GEN-END:initComponents

private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

    if ( radioET.isSelected() ) {
        painelGrafico.setTipoGrafico( PainelGrafico.TipoGrafico.ET );
    } else if ( radioAT.isSelected() ) {
        painelGrafico.setTipoGrafico( PainelGrafico.TipoGrafico.AT );
    } else {
        painelGrafico.setTipoGrafico( PainelGrafico.TipoGrafico.VT );
    }
    
    painelGrafico.setCorPontosET( painelCorET.getBackground() );
    painelGrafico.setCorPontosAT( painelCorAT.getBackground() );
    painelGrafico.setCorPontosVT( painelCorVT.getBackground() );
    
    painelGrafico.setMostrarValores( checkMostrarValores.isSelected() );
    
    dispose();
    
}//GEN-LAST:event_btnOKActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

private void painelCorATMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorATMouseClicked

    Color c = JColorChooser.showDialog( 
            this, "Cor AxT", painelCorAT.getBackground() );
    
    if ( c != null ) {
        painelCorAT.setBackground( c );
    }
    
}//GEN-LAST:event_painelCorATMouseClicked

private void painelCorVTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorVTMouseClicked

    Color c = JColorChooser.showDialog( 
            this, "Cor VxT", painelCorVT.getBackground() );
    
    if ( c != null ) {
        painelCorVT.setBackground( c );
    }
    
}//GEN-LAST:event_painelCorVTMouseClicked

private void painelCorETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorETMouseClicked

    Color c = JColorChooser.showDialog( 
            this, "Cor ExT", painelCorET.getBackground() );
    
    if ( c != null ) {
        painelCorET.setBackground( c );
    }
    
}//GEN-LAST:event_painelCorETMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox checkMostrarValores;
    private javax.swing.JLabel labelCorAT;
    private javax.swing.JLabel labelCorET;
    private javax.swing.JLabel labelCorVT;
    private javax.swing.JPanel painelConfiguracoes;
    private javax.swing.JPanel painelCorAT;
    private javax.swing.JPanel painelCorET;
    private javax.swing.JPanel painelCorVT;
    private javax.swing.JPanel painelTipoDesenho;
    private javax.swing.JRadioButton radioAT;
    private javax.swing.JRadioButton radioET;
    private javax.swing.JRadioButton radioVT;
    // End of variables declaration//GEN-END:variables
}
