/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PainelPrincipal.java
 *
 * Created on May 10, 2011, 5:01:05 PM
 */
package projetofisicamovimento.ig;

import java.awt.Color;
import javax.swing.JColorChooser;
import projetofisicamovimento.modelo.Bola;

/**
 * Janela principal do sistema.
 *
 * @author David Buzatto
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private PainelDesenho painelDesenho;
    private Bola bola;
    private double x;
    private double y;
    private double velocidadeIniX;
    private double velocidadeIniY;
    private double aceleracaoX;
    private double aceleracaoY;
    private double largura;
    private double altura;
    private int quadrosPorSegundo;
    private boolean executar;
    
    
    /** Creates new form PainelPrincipal */
    public JanelaPrincipal() {
        initComponents();
        preparar();
    }
    
    private void preparar() {
        
        painelDesenho = ( PainelDesenho ) painelMovimento;
        
        bola = new Bola();
        
        atualizarValores();
        painelDesenho.setSprite( bola );
        painelDesenho.setDesenharAjuda( true );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMovimento = new PainelDesenho();
        painelControle = new javax.swing.JPanel();
        painelPosicoes = new javax.swing.JPanel();
        labelPosIni = new javax.swing.JLabel();
        fieldPosIniX = new javax.swing.JTextField();
        labelPosIniX = new javax.swing.JLabel();
        fieldPosIniY = new javax.swing.JTextField();
        labelPosIniY = new javax.swing.JLabel();
        painelControleMovimento = new javax.swing.JPanel();
        labelVelX = new javax.swing.JLabel();
        labelVel = new javax.swing.JLabel();
        fieldVelY = new javax.swing.JTextField();
        fieldAcY = new javax.swing.JTextField();
        labelAcY = new javax.swing.JLabel();
        labelAc = new javax.swing.JLabel();
        fieldAcX = new javax.swing.JTextField();
        fieldVelX = new javax.swing.JTextField();
        labelVelY = new javax.swing.JLabel();
        labelAcX = new javax.swing.JLabel();
        painelTamanho = new javax.swing.JPanel();
        labelLargura = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        fieldLargura = new javax.swing.JTextField();
        fieldAltura = new javax.swing.JTextField();
        painelOutrasOpcoes = new javax.swing.JPanel();
        labelQuadSeg = new javax.swing.JLabel();
        fieldQuadSeg = new javax.swing.JTextField();
        checkMostrarMarcacoes = new javax.swing.JCheckBox();
        labelCorPreenchimento = new javax.swing.JLabel();
        painelCorPreenchimento = new javax.swing.JPanel();
        labelCorContorno = new javax.swing.JLabel();
        painelCorContorno = new javax.swing.JPanel();
        btnReconfigurar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto de Física - Movimentos");

        javax.swing.GroupLayout painelMovimentoLayout = new javax.swing.GroupLayout(painelMovimento);
        painelMovimento.setLayout(painelMovimentoLayout);
        painelMovimentoLayout.setHorizontalGroup(
            painelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        painelMovimentoLayout.setVerticalGroup(
            painelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        painelControle.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle"));

        painelPosicoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Posições"));

        labelPosIni.setText("Posição Inicial:");

        fieldPosIniX.setText("100.0");

        labelPosIniX.setText("x");

        fieldPosIniY.setText("340.0");

        labelPosIniY.setText("y");

        javax.swing.GroupLayout painelPosicoesLayout = new javax.swing.GroupLayout(painelPosicoes);
        painelPosicoes.setLayout(painelPosicoesLayout);
        painelPosicoesLayout.setHorizontalGroup(
            painelPosicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPosicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPosIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPosicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldPosIniX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPosIniX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPosicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldPosIniY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPosIniY))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPosicoesLayout.setVerticalGroup(
            painelPosicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPosicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPosicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosIni)
                    .addComponent(fieldPosIniX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPosIniY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(painelPosicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosIniX)
                    .addComponent(labelPosIniY))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        painelControleMovimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle do Movimento"));

        labelVelX.setText("x");

        labelVel.setText("Velocidade Inicial:");

        fieldVelY.setText("1.0");

        fieldAcY.setText("0.01");

        labelAcY.setText("y");

        labelAc.setText("Aceleração:");

        fieldAcX.setText("0.01");

        fieldVelX.setText("1.0");

        labelVelY.setText("y");

        labelAcX.setText("x");

        javax.swing.GroupLayout painelControleMovimentoLayout = new javax.swing.GroupLayout(painelControleMovimento);
        painelControleMovimento.setLayout(painelControleMovimentoLayout);
        painelControleMovimentoLayout.setHorizontalGroup(
            painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControleMovimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldVelX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVelX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldVelY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVelY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldAcX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAcX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelAcY)
                    .addComponent(fieldAcY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelControleMovimentoLayout.setVerticalGroup(
            painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControleMovimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelControleMovimentoLayout.createSequentialGroup()
                        .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldVelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldVelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVelX)
                            .addComponent(labelVelY)))
                    .addGroup(painelControleMovimentoLayout.createSequentialGroup()
                        .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAcX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAcY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelControleMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAcX)
                            .addComponent(labelAcY))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTamanho.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamanho"));

        labelLargura.setText("Largura:");

        labelAltura.setText("Altura:");

        fieldLargura.setText("10");

        fieldAltura.setText("10");

        javax.swing.GroupLayout painelTamanhoLayout = new javax.swing.GroupLayout(painelTamanho);
        painelTamanho.setLayout(painelTamanhoLayout);
        painelTamanhoLayout.setHorizontalGroup(
            painelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTamanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAltura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLargura, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldAltura)
                    .addComponent(fieldLargura, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTamanhoLayout.setVerticalGroup(
            painelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTamanhoLayout.createSequentialGroup()
                .addGroup(painelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLargura)
                    .addComponent(fieldLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltura)
                    .addComponent(fieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelOutrasOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Outras Opções"));

        labelQuadSeg.setText("Quadros por Segundo:");

        fieldQuadSeg.setText("30");

        checkMostrarMarcacoes.setSelected(true);
        checkMostrarMarcacoes.setText("Mostrar Marcações");
        checkMostrarMarcacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMostrarMarcacoesActionPerformed(evt);
            }
        });

        labelCorPreenchimento.setText("Cor do Preenchimento:");

        painelCorPreenchimento.setBackground(new java.awt.Color(0, 153, 204));
        painelCorPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelCorPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorPreenchimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorPreenchimentoLayout = new javax.swing.GroupLayout(painelCorPreenchimento);
        painelCorPreenchimento.setLayout(painelCorPreenchimentoLayout);
        painelCorPreenchimentoLayout.setHorizontalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorPreenchimentoLayout.setVerticalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        labelCorContorno.setText("Cor do Contorno:");

        painelCorContorno.setBackground(new java.awt.Color(0, 0, 0));
        painelCorContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelCorContorno.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorContorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorContornoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorContornoLayout = new javax.swing.GroupLayout(painelCorContorno);
        painelCorContorno.setLayout(painelCorContornoLayout);
        painelCorContornoLayout.setHorizontalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        painelCorContornoLayout.setVerticalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelOutrasOpcoesLayout = new javax.swing.GroupLayout(painelOutrasOpcoes);
        painelOutrasOpcoes.setLayout(painelOutrasOpcoesLayout);
        painelOutrasOpcoesLayout.setHorizontalGroup(
            painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOutrasOpcoesLayout.createSequentialGroup()
                .addGroup(painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelOutrasOpcoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCorContorno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCorPreenchimento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelQuadSeg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelCorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldQuadSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelOutrasOpcoesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(checkMostrarMarcacoes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelOutrasOpcoesLayout.setVerticalGroup(
            painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOutrasOpcoesLayout.createSequentialGroup()
                .addGroup(painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuadSeg)
                    .addComponent(fieldQuadSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkMostrarMarcacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorPreenchimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOutrasOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(painelCorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorContorno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReconfigurar.setText("Reconfigurar");
        btnReconfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconfigurarActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnParar.setText("Parar");
        btnParar.setEnabled(false);
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelControleLayout = new javax.swing.GroupLayout(painelControle);
        painelControle.setLayout(painelControleLayout);
        painelControleLayout.setHorizontalGroup(
            painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControleLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelControleLayout.createSequentialGroup()
                        .addComponent(painelTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelOutrasOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReconfigurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParar))
                    .addGroup(painelControleLayout.createSequentialGroup()
                        .addComponent(painelPosicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelControleMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        painelControleLayout.setVerticalGroup(
            painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControleLayout.createSequentialGroup()
                .addGroup(painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelPosicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(painelControleMovimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelOutrasOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelControleLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIniciar)
                            .addComponent(btnReconfigurar)
                            .addComponent(btnParar)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelMovimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelMovimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-881)/2, (screenSize.height-519)/2, 881, 519);
    }// </editor-fold>//GEN-END:initComponents

    private void checkMostrarMarcacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostrarMarcacoesActionPerformed
        if ( checkMostrarMarcacoes.isSelected() ) {
            painelDesenho.setDesenharAjuda( true );
        } else {
            painelDesenho.setDesenharAjuda( false );
        }
        painelDesenho.repaint();
    }//GEN-LAST:event_checkMostrarMarcacoesActionPerformed

    private void painelCorPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorPreenchimentoMouseClicked
        
        Color c = JColorChooser.showDialog( this, "Cor do Preenchimento", painelCorPreenchimento.getBackground() );
        
        if ( c != null ) {
            painelCorPreenchimento.setBackground( c );
            bola.setCorPreenchimento( c );
            painelDesenho.repaint();
        }
        
    }//GEN-LAST:event_painelCorPreenchimentoMouseClicked

    private void painelCorContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorContornoMouseClicked
        
        Color c = JColorChooser.showDialog( this, "Cor do Contorno", painelCorContorno.getBackground() );
        
        if ( c != null ) {
            painelCorContorno.setBackground( c );
            bola.setCorContorno( c );
            painelDesenho.repaint();
        }
        
    }//GEN-LAST:event_painelCorContornoMouseClicked

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        atualizarValores();
        new Thread( new Animador() ).start();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnReconfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconfigurarActionPerformed
        atualizarValores();
        btnIniciar.setEnabled( true );
    }//GEN-LAST:event_btnReconfigurarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        executar = false;
    }//GEN-LAST:event_btnPararActionPerformed

    private void atualizarValores() {
        
        try {
            largura = Double.parseDouble( fieldLargura.getText() );
        } catch ( NumberFormatException exc ) {
            fieldLargura.setText( String.valueOf( largura ) );
        }
        
        bola.setLargura( largura );
        
        
        
        try {
            altura = Double.parseDouble( fieldAltura.getText() );
        } catch ( NumberFormatException exc ) {
            fieldAltura.setText( String.valueOf( altura ) );
        }
        
        bola.setAltura( altura );
        
        
        
        try {
            x = Double.parseDouble( fieldPosIniX.getText() );
        } catch ( NumberFormatException exc ) {
            fieldPosIniX.setText( String.valueOf( x ) );
        }
        
        bola.setX( x );
        painelDesenho.setXIni( bola.getX() );
        
        
        
        try {
            y = Double.parseDouble( fieldPosIniY.getText() );
        } catch ( NumberFormatException exc ) {
            fieldPosIniY.setText( String.valueOf( y ) );
        }
        
        bola.setY( y );
        painelDesenho.setYIni( bola.getYCentro() );
        
        
        
        try {
            velocidadeIniX = Double.parseDouble( fieldVelX.getText() );
        } catch ( NumberFormatException exc ) {
            fieldVelX.setText( String.valueOf( velocidadeIniX ) );
        }
        
        bola.setVelocidadeX( velocidadeIniX );
        
        
        
        try {
            velocidadeIniY = Double.parseDouble( fieldVelY.getText() );
        } catch ( NumberFormatException exc ) {
            fieldVelY.setText( String.valueOf( velocidadeIniY ) );
        }
        
        bola.setVelocidadeY( velocidadeIniY );
        
        
        
        try {
            aceleracaoX = Double.parseDouble( fieldAcX.getText() );
        } catch ( NumberFormatException exc ) {
            fieldAcX.setText( String.valueOf( aceleracaoX ) );
        }
        
        bola.setAceleracaoX( aceleracaoX );
        
        
        
        try {
            aceleracaoY = Double.parseDouble( fieldAcY.getText() );
        } catch ( NumberFormatException exc ) {
            fieldAcY.setText( String.valueOf( aceleracaoY ) );
        }
        
        bola.setAceleracaoY( aceleracaoY );
        
        
        
        try {
            quadrosPorSegundo = Integer.parseInt( fieldQuadSeg.getText() );
        } catch ( NumberFormatException exc ) {
            fieldQuadSeg.setText( String.valueOf( quadrosPorSegundo ) );
        }
        
        
        
        bola.setCorPreenchimento( painelCorPreenchimento.getBackground() );
        bola.setCorContorno( painelCorContorno.getBackground() );
        painelDesenho.getTragetoria().limparPontos();
        
        painelDesenho.repaint();
        
    }

    private class Animador implements Runnable {

        public void run() {
            
            // tempo de execução em milisegundos
            double tempo = 0;
            
            executar = true;

            fieldPosIniX.setEditable( false );
            fieldPosIniY.setEditable( false );
            fieldVelX.setEditable( false );
            fieldVelY.setEditable( false );
            fieldAcX.setEditable( false );
            fieldAcY.setEditable( false );
            fieldLargura.setEditable( false );
            fieldAltura.setEditable( false );
            fieldQuadSeg.setEditable( false );
            btnReconfigurar.setEnabled( false );
            btnIniciar.setEnabled( false );
            btnParar.setEnabled( true );

            while ( executar ) {
                
                /********************************************
                 ****** início do código do movimento *******
                 ********************************************/
                
                 
                /*// MRU e MRUV
                
                // calculando a velocidade atual
                double velocidadeX = velocidadeIniX + aceleracaoX * tempo;
                // precisa inverter y por causa do sistema de coordenadas.
                double velocidadeY = - ( velocidadeIniY + aceleracaoY * tempo );
                
                // muda a velocidade atual da bola
                bola.setVelocidadeX( velocidadeX );
                bola.setVelocidadeY( velocidadeY );
                
                // muda a posição atual da bola, baseada na velocidade
                // configurada anteriormente
                bola.setX( bola.getX() + bola.getVelocidadeX() );
                bola.setY( bola.getY() + bola.getVelocidadeY() );*/
                
                
                
                
                /*// queda livre
                
                // calculando a velocidade atual                
                double gravidade = 0.01;
                double velocidadeX = velocidadeIniX;
                // precisa inverter y por causa do sistema de coordenadas.
                double velocidadeY = - ( ( gravidade * tempo * tempo ) / 2 );
                
                // muda a velocidade atual da bola
                bola.setVelocidadeX( velocidadeX );
                bola.setVelocidadeY( velocidadeY );
                
                // muda a posição atual da bola, baseada na velocidade
                // configurada anteriormente
                bola.setX( bola.getX() + bola.getVelocidadeX() );
                bola.setY( bola.getY() + bola.getVelocidadeY() );*/
                
                
                
                 
                // projétil
                
                // calculando a velocidade atual
                double angulo = 60;
                double gravidade = 0.01;
                double velocidadeX = velocidadeIniX * Math.cos( Math.toRadians( angulo ) ) * tempo;
                // precisa inverter y por causa do sistema de coordenadas.
                double velocidadeY = - ( velocidadeIniY * Math.sin( Math.toRadians( angulo ) ) * tempo - ( ( ( gravidade / 2 ) * tempo * tempo ) ) );
                
                // muda a velocidade atual da bola
                bola.setVelocidadeX( velocidadeX );
                bola.setVelocidadeY( velocidadeY );
                
                // muda a posição atual da bola, baseada na velocidade
                // configurada anteriormente
                bola.setX( bola.getX() + bola.getVelocidadeX() );
                bola.setY( bola.getY() + bola.getVelocidadeY() );
                
                
                
                
                /********************************************
                 ******* fim do código do movimento *********
                 ********************************************/
                
                painelDesenho.getTragetoria().adicionarPonto( 
                        bola.getXCentro(), bola.getYCentro() );
                
                tempo += 1000 / quadrosPorSegundo;
                
                if ( bola.getXFim() > painelMovimento.getWidth() ) {

                    bola.setX( painelMovimento.getWidth() - bola.getLargura() );
                    executar = false;

                }
                
                if ( bola.getX() < 0 ) {

                    bola.setX( 0 );
                    executar = false;

                }
                
                if ( bola.getYFim() > painelMovimento.getHeight() ) {

                    bola.setY( painelMovimento.getHeight() - bola.getAltura()  );
                    executar = false;

                }

                if ( bola.getY() < 0 ) {

                    bola.setY( 0 );
                    executar = false;

                }
                
                painelDesenho.repaint();
                
                try {
                    Thread.sleep( 1000 / quadrosPorSegundo );
                } catch ( InterruptedException exc ) {
                    exc.printStackTrace();
                }

            }
            
            fieldPosIniX.setEditable( true );
            fieldPosIniY.setEditable( true );
            fieldVelX.setEditable( true );
            fieldVelY.setEditable( true );
            fieldAcX.setEditable( true );
            fieldAcY.setEditable( true );
            fieldLargura.setEditable( true );
            fieldAltura.setEditable( true );
            fieldQuadSeg.setEditable( true );
            btnReconfigurar.setEnabled( true );
            btnIniciar.setEnabled( true );
            btnParar.setEnabled( false );

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnReconfigurar;
    private javax.swing.JCheckBox checkMostrarMarcacoes;
    private javax.swing.JTextField fieldAcX;
    private javax.swing.JTextField fieldAcY;
    private javax.swing.JTextField fieldAltura;
    private javax.swing.JTextField fieldLargura;
    private javax.swing.JTextField fieldPosIniX;
    private javax.swing.JTextField fieldPosIniY;
    private javax.swing.JTextField fieldQuadSeg;
    private javax.swing.JTextField fieldVelX;
    private javax.swing.JTextField fieldVelY;
    private javax.swing.JLabel labelAc;
    private javax.swing.JLabel labelAcX;
    private javax.swing.JLabel labelAcY;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCorContorno;
    private javax.swing.JLabel labelCorPreenchimento;
    private javax.swing.JLabel labelLargura;
    private javax.swing.JLabel labelPosIni;
    private javax.swing.JLabel labelPosIniX;
    private javax.swing.JLabel labelPosIniY;
    private javax.swing.JLabel labelQuadSeg;
    private javax.swing.JLabel labelVel;
    private javax.swing.JLabel labelVelX;
    private javax.swing.JLabel labelVelY;
    private javax.swing.JPanel painelControle;
    private javax.swing.JPanel painelControleMovimento;
    private javax.swing.JPanel painelCorContorno;
    private javax.swing.JPanel painelCorPreenchimento;
    private javax.swing.JPanel painelMovimento;
    private javax.swing.JPanel painelOutrasOpcoes;
    private javax.swing.JPanel painelPosicoes;
    private javax.swing.JPanel painelTamanho;
    // End of variables declaration//GEN-END:variables
}
